### ISSUE TITLE
display_name becomes non searchable once this module is installed

### ISSUE THREAD

**Issue by farazbdm** [OCA/multi-company#84] opened 2018-02-10 14:34 UTC
this module makes the partner display_name field to be non-stored and thus the search function of partner on the display_name becomes invalid resulting in following error:

ERROR database odoo.osv.expression: Non-stored field res.partner.display_name cannot be searched.

**Comment by pedrobaeza** [comment] 2018-02-10 15:04
Which module?

**Comment by pedroortega-punt** [comment] 2018-05-15 07:50
Buenos días,

@pedrobaeza 

Cuando se instala el módulo "partner_multi_company" la búsqueda por nombre en clientes deja de funcionar, y en la vista tree no deja ordenar por nombre.

**Comment by pedroortega-punt** [comment] 2018-05-15 07:50
V10

**Comment by pedrobaeza** [comment] 2018-05-15 08:00
Only in English, please. I'm looking at the module and dependencies and it doesn't change anything about display_name.

**Comment by pedroortega-punt** [comment] 2018-05-15 14:03
Good Morning,

@pedrobaeza

When the "partner_multi_company" module is installed, the search by name in clients stops working, and in the tree view it does not allow to sort by name.

**Comment by pedrobaeza** [comment] 2018-05-15 14:04
As already said, there's seems to be no relation on that, as neither name nor display_name fields are touched in this module.

**Comment by pedroortega-punt** [comment] 2018-05-15 14:10
@pedrobaeza 

I'm not a programmer, they're a consultant. But I can assure you that at the moment you install the partner_multi_company module, the search by name and sort by name will stop working.

Also if you uninstall the module after associating several companies in a partner and want to install again, you get a message that can not be installed because a partner has two companies, so I infer that the relationship table does not eliminate the ids when it is uninstalled, then it does not let you install any more.

**Comment by pedrobaeza** [comment] 2018-05-15 15:03
You can try in http://3326111-10-0-f60542.runbot1.odoo-community.org/web#min=1&limit=80&view_type=list&model=res.partner&menu_id=112&action=56, that is the current 10.0 OCA runbot, where the module is installed, and everything is working fine, so please be sure before posting issues about what is the real problem.

**Comment by pedroortega-punt** [comment] 2018-05-15 15:33
@pedrobaeza 

Sorry,

I had checked it perfectly and it does not work, what should have been detailed in which menu, in the accounting / clients if it works, in the sales / clients does not work.

**Comment by pedroortega-punt** [comment] 2018-05-15 15:34
You can try in http://3326111-10-0-f60542.runbot1.odoo-community.org/web#min=1&limit=80&view_type=list&model=res.partner&menu_id=189&action=55

**Comment by pedrobaeza** [comment] 2018-05-15 18:09
OK, reopening the issue, but I haven't checked the root cause.

**Comment by Iskander-NSK** [comment] 2018-05-17 10:54
I have this problem too. Source of the problem - hooks.py
post_init_hook - do not allow next installation after uninstall module; display_name becomes non searchable after 1-st installation.
uninstall_hook - display_name becomes clean after module uninstall.
But I'm not programmer and do not know what to do next.
I hope this information will allow find the problem.

**Comment by Iskander-NSK** [comment] 2018-05-18 02:19
Repeat installation failed after install and uninstall module without hooks.py...
I'm confused...

**Comment by Iskander-NSK** [comment] 2018-05-18 06:13
So ... the problem of stopping search by the display_field is associated with the inheritance of the model multi.company.abstract in partner_multi_company/models/res_partner.py
I will clarify some points: if you disable the import of methods from the file partner_multi_company/hooks.py, the module is installed and uninstalled without problems;
but after it is installed, the search for display_name in contacts does not work.

**Comment by Iskander-NSK** [comment] 2018-05-21 03:13
Search work succesfully.
in res_partner.py need to add string:
display_name = fields.Char(string='Display Name', compute='_compute_display_name', store=True)
and in import section need to add fields.

P.S. hooks.py till disabled because otherwise error if the module installed after uninstall. 
Error:" The operation cannot be completed, probably due to the following:
- deletion: you may be trying to delete a record while other records still reference it
- creation/update: a mandatory field is not correctly set.
[object with reference:res_company_assignment_id - res.company.assignment.id]

**Comment by farazbdm** [comment] 2018-05-24 22:15
@Iskander-NSK 
can you please provide a code fix as per above instruction if it fixes the issue.

**Comment by igallart** [comment] 2018-06-12 15:17
This is a possible solution.
https://github.com/OCA/multi-company/pull/103

**Comment by pedroortega-punt** [comment] 2018-06-19 18:37
Is @igallart solution correct?

**Comment by pedrobaeza** [comment] 2018-06-19 22:56
I don't see it clear. I have asked on the PR itself.

**Comment by farazbdm** [comment] 2018-06-26 21:22
@vipvalen  yes the solution by @igallart  worked with me. Thanks alot.

**Comment by pedroortega-punt** [comment] 2018-08-03 06:20
@pedrobaeza 
The igallart solution is working correctly on my client, can you please do the merge?

**Comment by mdmfox** [comment] 2018-09-01 07:59
Hey guys, any updates about this issue?
I have installed the solution by @igallart and it worked on my server.
However, I saw the some test checks were not successful; and in my case it erased the res_partner display_name. 
Anyways, thanks!!

**Comment by igallart** [comment] 2018-09-01 11:50
@mdmfox, with display_name erased, the search in partners of sales worked when you search by name?

**Comment by mdmfox** [comment] 2018-09-12 04:36
Hi @igallart, the search in partners only works by email after the change, by the settings at the view id="view_res_partner_filter". But exactly, because in my case, there was no filled register with display_name.
After I update 'res_partner.display_name' from 'res_partner.name' everything was working perfectly.

**Comment by LoisRForgeFlow** [comment] 2019-10-22 08:09
I can confirm this issue also happens in v11, I also tested in runbot, this is what happens after the installation of the module partner_multi_company:
![picture-2019-22-10](https://user-images.githubusercontent.com/23449160/67268106-f946c980-f4b3-11e9-9851-59aa9718c4f9.png)

~In v12 seems correct though.~ EDIT: it happens.

**Comment by pedrobaeza** [comment] 2019-10-23 11:44
Fixed in #165

**Closed as completed by pedrobaeza** 2019-10-23 11:44 UTC

**Comment by thomaspaulb** [comment] 2020-07-08 13:07
It seems this is a bug in Odoo itself. I think that because the `display_name` was [changed to an automatic field](https://github.com/OCA/OCB/blob/10.0/odoo/models.py#L438), and [automatic fields dont inherit properties](https://github.com/OCA/OCB/blob/10.0/odoo/fields.py#L438), the "store" property on res.partner gets lost along the way.

Adding a line of `display_name = fields.Char(compute='_compute_display_name', store=True, index=True)` on `res.partner` in any module further along the inheritance chain is a workaround, but I dont think it has anything to do with `partner_multi_company`.
